### ISSUE TITLE
[New track] giveaway/keyhub

### ISSUE THREAD

**Issue by arseny92** [CutieCafe/gloss#2]
Site to add: https://key-hub.eu/
Suggested key: giveaway/keyhub
Notes: dislikes adblockers, VPNs and IPv6 tunnels

**Comment by antigravities** [comment]
Staged for 1.3.33 via 9c6c22a14f0e89177a1d9a2df434f856c9256d86, antigravities/gloss@a9c141dd7b8fa5c7b3c0839e9bdb36248983880a
