### ISSUE TITLE
[New track] giveaway/steelseries

### ISSUE THREAD

**Issue by arseny92** [CutieCafe/gloss#3]
Site to add: https://games.steelseries.com/home
Pattern: https://games.steelseries.com/giveaway/{id}/details - id numeric
Suggested key: giveaway/steelseries
Notes: SteelSeries reboot

**Comment by antigravities** [comment]
Staged for 1.3.33 via antigravities/gloss@35aa597f90403a433de7afcf9a6147cf28fa5864
